# Generated by Django 4.2 on 2023-05-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageServer', '0005_alter_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
