# Generated by Django 4.2 on 2023-05-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageServer', '0008_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='group_pictures'),
        ),
    ]
