# Generated by Django 4.2 on 2023-05-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageServer', '0009_group_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='conversation_pictures'),
        ),
    ]
