# Generated by Django 4.2 on 2023-05-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageServer', '0012_alter_conversation_id_alter_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_registration_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='messageServer.group'),
        ),
    ]
